### PR TITLE
Issue 19,18

### PR DESCRIPTION
**Pull request by nithu0115**
Ref: issue#19,#18

### CODE REVIEW

**Comment by rimaulana** [comment]
Verified to be working by testing it on
- amazon-eks-node-1.11-v20190614
- amazon-eks-node-1.12-v20190614
- amazon-eks-node-1.13-v20190614

Running aws-vpc-cni v1.4.1

**Review by rimaulana — APPROVED** [review]
/LGTM

**Comment by nithu0115** [comment]
Thanks @rimaulana

**Pull request merged**
